apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: gateway-api-controller
  name: gateway-api-controller-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: gateway-api-controller
